// Code in this package follows the shape generated by sqlc from query.sql.
// Regenerate with `sqlc generate` after changing schema.sql or query.sql.
package db

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

type Queries struct {
	db DBTX
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func (q *Queries) DBTX() DBTX {
	return q.db
}

func PrepareSchema(ctx context.Context, database *sql.DB) error {
	_, err := database.ExecContext(ctx, `
CREATE TABLE IF NOT EXISTS runtime_settings (
    key TEXT PRIMARY KEY,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS identity_sources (
    slug TEXT PRIMARY KEY,
    provider_type TEXT NOT NULL,
    display_name TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    login_enabled INTEGER NOT NULL DEFAULT 1,
    directory_sync_enabled INTEGER NOT NULL DEFAULT 1,
    config_json TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS external_accounts (
    id TEXT PRIMARY KEY,
    provider_slug TEXT NOT NULL,
    subject TEXT NOT NULL,
    subject_norm TEXT NOT NULL,
    subject_type TEXT NOT NULL,
    app_identity_id TEXT,
    display_name TEXT,
    email TEXT,
    email_norm TEXT,
    email_verified INTEGER,
    mobile_masked TEXT,
    avatar_url TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    last_login_at TEXT,
    last_seen_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(provider_slug, subject_norm)
);
CREATE TABLE IF NOT EXISTS app_identities (
    id TEXT PRIMARY KEY,
    display_name TEXT,
    primary_email TEXT,
    primary_email_norm TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    created_by TEXT NOT NULL DEFAULT 'system',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS dsm_accounts (
    id TEXT PRIMARY KEY,
    app_identity_id TEXT NOT NULL UNIQUE,
    dsm_username TEXT NOT NULL,
    dsm_username_norm TEXT NOT NULL UNIQUE,
    managed INTEGER NOT NULL DEFAULT 1,
    provision_status TEXT NOT NULL DEFAULT 'pending',
    allow_login INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS provider_groups (
    id TEXT PRIMARY KEY,
    provider_slug TEXT NOT NULL,
    subject TEXT NOT NULL,
    subject_norm TEXT NOT NULL,
    parent_subject TEXT,
    name TEXT NOT NULL,
    path TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(provider_slug, subject_norm)
);
CREATE TABLE IF NOT EXISTS dsm_groups (
    id TEXT PRIMARY KEY,
    dsm_groupname TEXT NOT NULL,
    dsm_groupname_norm TEXT NOT NULL UNIQUE,
    managed INTEGER NOT NULL DEFAULT 1,
    provision_status TEXT NOT NULL DEFAULT 'pending',
    conflict_reason TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS group_links (
    id TEXT PRIMARY KEY,
    provider_group_id TEXT NOT NULL,
    dsm_group_id TEXT NOT NULL,
    link_mode TEXT NOT NULL DEFAULT 'managed',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(provider_group_id, dsm_group_id)
);
CREATE TABLE IF NOT EXISTS group_members (
    id TEXT PRIMARY KEY,
    dsm_group_id TEXT NOT NULL,
    dsm_account_id TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    provision_status TEXT NOT NULL DEFAULT 'pending',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(dsm_group_id, dsm_account_id)
);
CREATE TABLE IF NOT EXISTS sync_runs (
    id TEXT PRIMARY KEY,
    source_slug TEXT NOT NULL,
    dry_run INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TEXT,
    error TEXT
);
CREATE TABLE IF NOT EXISTS sync_operation_logs (
    id TEXT PRIMARY KEY,
    sync_run_id TEXT NOT NULL,
    source_slug TEXT NOT NULL,
    object_type TEXT NOT NULL,
    object_key TEXT NOT NULL,
    dsm_name TEXT,
    action TEXT NOT NULL,
    status TEXT NOT NULL,
    before_state TEXT,
    after_state TEXT,
    error TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS login_audit_logs (
    id TEXT PRIMARY KEY,
    request_id TEXT NOT NULL,
    provider_slug TEXT NOT NULL,
    external_account_id TEXT,
    app_identity_id TEXT,
    dsm_username TEXT,
    result TEXT NOT NULL,
    error_code TEXT,
    ip_address TEXT,
    ip_hash TEXT,
    user_agent_hash TEXT,
    duration_ms INTEGER,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`)
	if err != nil {
		return err
	}
	_, _ = database.ExecContext(ctx, `ALTER TABLE group_members ADD COLUMN active INTEGER NOT NULL DEFAULT 1`)
	_, _ = database.ExecContext(ctx, `ALTER TABLE login_audit_logs ADD COLUMN ip_address TEXT`)
	return nil
}
