package backend

import (
	"database/sql"
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gin-gonic/gin"

	"github.com/dsmpass/dsmpass/go/internal/db"
)

func (s *Server) providers(c *gin.Context) {
	items := []gin.H{}
	rows, err := s.store.DBTX().QueryContext(c.Request.Context(), `
SELECT slug, provider_type, display_name, enabled, login_enabled, directory_sync_enabled, config_json, created_at, updated_at
FROM identity_sources
ORDER BY created_at`)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	defer rows.Close()
	for rows.Next() {
		var source db.IdentitySource
		if err := rows.Scan(&source.Slug, &source.ProviderType, &source.DisplayName, &source.Enabled, &source.LoginEnabled, &source.DirectorySyncEnabled, &source.ConfigJSON, &source.CreatedAt, &source.UpdatedAt); err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
			return
		}
		config := decodeSourceConfig(source.ConfigJSON)
		items = append(items, sourceResponse(source, config, s.trustedPublicBaseURL()))
	}
	if rows.Err() != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": rows.Err().Error()})
		return
	}
	c.JSON(http.StatusOK, gin.H{"items": items})
}

func (s *Server) createProvider(c *gin.Context) {
	var payload struct {
		Slug                 *string              `json:"slug"`
		ProviderType         string               `json:"provider_type"`
		DisplayName          string               `json:"display_name"`
		Enabled              *bool                `json:"enabled"`
		LoginEnabled         *bool                `json:"login_enabled"`
		DirectorySyncEnabled *bool                `json:"directory_sync_enabled"`
		Config               identitySourceConfig `json:"config"`
	}
	if err := c.BindJSON(&payload); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"detail": "invalid json"})
		return
	}
	if payload.Slug != nil {
		c.JSON(http.StatusBadRequest, gin.H{"detail": "identity source slug is generated by the server and must not be provided"})
		return
	}
	if payload.DisplayName == "" {
		c.JSON(http.StatusBadRequest, gin.H{"detail": "identity source display name is required"})
		return
	}
	slug, err := randomUUID()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": "failed to generate identity source id"})
		return
	}
	if payload.ProviderType == "" {
		payload.ProviderType = "feishu"
	}
	if !supportedProviderType(payload.ProviderType) {
		c.JSON(http.StatusBadRequest, gin.H{"detail": "unsupported provider type"})
		return
	}
	config := withSourceDefaults(payload.Config)
	configJSON, err := json.Marshal(config)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"detail": err.Error()})
		return
	}
	_, err = s.store.DBTX().ExecContext(c.Request.Context(), `
INSERT INTO identity_sources (slug, provider_type, display_name, enabled, login_enabled, directory_sync_enabled, config_json, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
`, slug, payload.ProviderType, payload.DisplayName, boolPtrInt(payload.Enabled, true), boolPtrInt(payload.LoginEnabled, true), boolPtrInt(payload.DirectorySyncEnabled, true), string(configJSON))
	if err != nil {
		c.JSON(http.StatusConflict, gin.H{"detail": err.Error()})
		return
	}
	s.getProvider(c, slug)
}

func (s *Server) updateProvider(c *gin.Context) {
	slug := c.Param("slug")
	source, err := s.loadIdentitySource(c.Request.Context(), slug)
	if err == sql.ErrNoRows {
		c.JSON(http.StatusNotFound, gin.H{"detail": "identity source not found"})
		return
	}
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	var payload struct {
		DisplayName          *string               `json:"display_name"`
		Enabled              *bool                 `json:"enabled"`
		LoginEnabled         *bool                 `json:"login_enabled"`
		DirectorySyncEnabled *bool                 `json:"directory_sync_enabled"`
		Config               *identitySourceConfig `json:"config"`
	}
	if err := c.BindJSON(&payload); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"detail": "invalid json"})
		return
	}
	displayName := source.DisplayName
	if payload.DisplayName != nil && strings.TrimSpace(*payload.DisplayName) != "" {
		displayName = strings.TrimSpace(*payload.DisplayName)
	}
	config := decodeSourceConfig(source.ConfigJSON)
	if payload.Config != nil {
		config = mergeSourceConfig(config, *payload.Config)
	}
	configJSON, _ := json.Marshal(config)
	_, err = s.store.DBTX().ExecContext(c.Request.Context(), `
UPDATE identity_sources
SET display_name = ?, enabled = ?, login_enabled = ?, directory_sync_enabled = ?, config_json = ?, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?
`, displayName, boolPtrInt(payload.Enabled, source.Enabled == 1), boolPtrInt(payload.LoginEnabled, source.LoginEnabled == 1), boolPtrInt(payload.DirectorySyncEnabled, source.DirectorySyncEnabled == 1), string(configJSON), slug)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	s.getProvider(c, slug)
}

func (s *Server) deleteProvider(c *gin.Context) {
	slug := c.Param("slug")
	if _, err := s.loadIdentitySource(c.Request.Context(), slug); err == sql.ErrNoRows {
		c.JSON(http.StatusNotFound, gin.H{"detail": "identity source not found"})
		return
	} else if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	if s.database == nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": "database handle is not available"})
		return
	}
	tx, err := s.database.BeginTx(c.Request.Context(), nil)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	defer func() { _ = tx.Rollback() }()

	exclusiveIdentityIDs, providerGroupIDs, exclusiveGroupIDs, err := sourceOwnedIDs(c.Request.Context(), tx, slug)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	exclusiveAccountIDs, err := accountIDsForIdentities(c.Request.Context(), tx, exclusiveIdentityIDs)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	exclusiveAccountUsernames := []string{}
	if len(exclusiveAccountIDs) > 0 {
		exclusiveAccountUsernames, err = queryStringIDs(c.Request.Context(), tx, `
SELECT dsm_username FROM dsm_accounts
WHERE id IN (`+placeholders(len(exclusiveAccountIDs))+`)`, anySlice(exclusiveAccountIDs)...)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
			return
		}
	}
	disabledDSMUsers := int64(0)
	for _, username := range exclusiveAccountUsernames {
		if _, err := s.helper.DisableUser(c.Request.Context(), "delete_source_disable_"+randomHex(8), username); err != nil {
			c.JSON(http.StatusBadGateway, gin.H{"detail": "删除身份源前禁用 DSM 用户失败：" + err.Error()})
			return
		}
		disabledDSMUsers++
	}
	removedDSMGroupMembers, err := s.removeSourceGroupMembersFromDSM(c.Request.Context(), tx, slug, "delete_source_member_remove_")
	if err != nil {
		c.JSON(http.StatusBadGateway, gin.H{"detail": "删除身份源前移除 DSM 组成员失败：" + err.Error()})
		return
	}

	result, err := deleteIdentitySourceDataWithIDs(c.Request.Context(), tx, slug, exclusiveIdentityIDs, exclusiveAccountIDs, providerGroupIDs, exclusiveGroupIDs)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	sourceResult, err := tx.ExecContext(c.Request.Context(), `DELETE FROM identity_sources WHERE slug = ?`, slug)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	deletedSources, _ := sourceResult.RowsAffected()
	if err := tx.Commit(); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	result["slug"] = slug
	result["deleted_sources"] = deletedSources
	result["disabled_dsm_users"] = disabledDSMUsers
	result["removed_dsm_group_members"] = removedDSMGroupMembers
	result["detail"] = "已禁用 DSM 中对应用户，并删除身份源配置、本地同步映射和日志"
	c.JSON(http.StatusOK, result)
}

func (s *Server) sourceSyncRuns(c *gin.Context) {
	rows, err := queryJSON(c.Request.Context(), s.store, `
SELECT id, source_slug, dry_run, status, started_at, finished_at, error
FROM sync_runs
WHERE source_slug = ?
ORDER BY started_at DESC
LIMIT 50`, c.Param("slug"))
	writeItems(c, rows, err)
}

func (s *Server) sourceSyncLogs(c *gin.Context) {
	paging := parsePagination(c)
	whereParts := []string{`source_slug = ?`}
	args := []any{c.Param("slug")}
	switch status := strings.TrimSpace(c.Query("status")); status {
	case "", "all":
	default:
		whereParts = append(whereParts, `status = ?`)
		args = append(args, status)
	}
	if q := queryText(c); q != "" {
		pattern := likePattern(q)
		whereParts = append(whereParts, `(sync_run_id LIKE ? ESCAPE '\' OR object_type LIKE ? ESCAPE '\' OR object_key LIKE ? ESCAPE '\' OR dsm_name LIKE ? ESCAPE '\' OR action LIKE ? ESCAPE '\' OR status LIKE ? ESCAPE '\' OR before_state LIKE ? ESCAPE '\' OR after_state LIKE ? ESCAPE '\' OR error LIKE ? ESCAPE '\')`)
		args = append(args, pattern, pattern, pattern, pattern, pattern, pattern, pattern, pattern, pattern)
	}
	where := "WHERE " + strings.Join(whereParts, " AND ")
	total, err := queryCount(c.Request.Context(), s.store, `SELECT COUNT(*) FROM sync_operation_logs `+where, args...)
	if err != nil {
		writeItems(c, nil, err)
		return
	}
	dataArgs := append(append([]any{}, args...), paging.Limit, paging.Offset)
	rows, err := queryJSON(c.Request.Context(), s.store, `
SELECT id, sync_run_id, source_slug, object_type, object_key, dsm_name, action, status, before_state, after_state, error, created_at
FROM sync_operation_logs
`+where+`
ORDER BY created_at DESC
LIMIT ? OFFSET ?`, dataArgs...)
	writePagedItems(c, rows, total, paging, err)
}

func (s *Server) getProvider(c *gin.Context, slug string) {
	source, err := s.loadIdentitySource(c.Request.Context(), slug)
	if err == sql.ErrNoRows {
		c.JSON(http.StatusNotFound, gin.H{"detail": "identity source not found"})
		return
	}
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"detail": err.Error()})
		return
	}
	c.JSON(http.StatusOK, sourceResponse(source, decodeSourceConfig(source.ConfigJSON), s.trustedPublicBaseURL()))
}
